version: '3'

services:
  # Game server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_gs:v0.1
    volumes:
      - "${SHARED_DIR}/:/home"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: ${RESTART}
    links:
      - tlbbdb
      - webdb

  # Game database
  tlbbdb:
    build:
      context: ./tlbbdb
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_tlbbdbserver:v0.1
    volumes:
      - "${SHARED_DIR}/tlbbdb/mysql:/var/lib/mysql"
    ports:
      - "${TLBB_MYSQL_PORT}:${HOST_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "tlbbdb"
    restart: ${RESTART}

  # Web database
  webdb:
    build:
      context: ./webdb
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_webdbserver:v0.1
    volumes:
    - "${SHARED_DIR}/webdb/mysql:/var/lib/mysql"
    ports:
    - "${WEB_MYSQL_PORT}:${HOST_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "web"
    restart: ${RESTART}