version: '3'

services:
  # Game server
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_gs:v0.3
    volumes:
      - "${SHARED_DIR}/:/home"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${BILLING_PORT}:${BILLING_PORT}"
    restart: ${RESTART}
    links:
      - tlbbdb
      - webdb
  # Game database
  tlbbdb:
    build:
      context: ./services/tlbbdb
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_tlbbdbserver:v0.1
    volumes:
      - "${SHARED_DIR}/tlbbdb/mysql:/var/lib/mysql"
    ports:
      - "${TLBB_MYSQL_PORT}:${HOST_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${TLBBDB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "tlbbdb"
    restart: ${RESTART}
  # Web database
  webdb:
    build:
      context: ./services/webdb
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_webdbserver:v0.1
    volumes:
    - "${SHARED_DIR}/webdb/mysql:/var/lib/mysql"
    ports:
    - "${WEB_MYSQL_PORT}:${HOST_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${WEBDB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "web"
    restart: ${RESTART}

  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlnginx:v0.1
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    environment:
      TZ: "$TZ"
    restart: ${RESTART}

  php:
      build:
        context: ./services/php
      image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlphp:v0.1
      expose:
        - 9501
      restart: ${RESTART}