version: '3'

services:
  # Game server
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - "${SHARED_DIR}/:/home"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${BILLING_PORT}:${BILLING_PORT}"
    restart: ${RESTART}
    links:
      - tlmysql
      - nginx
  # Game database
  tlmysql:
    build:
      context: ./services/tlmysql
      dockerfile: Dockerfile
    volumes:
      - "${SHARED_DIR}/tlmysql/:/var/lib/mysql"
    ports:
      - "${TL_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${TL_MYSQL_PASSWORD}
      MYSQL_DATABASE: "tlbbdb"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: ${RESTART}
  # Web database
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    volumes:
    - "${SHARED_DIR}/www/:/var/www"
    ports:
    - "${WEBSERVER_PORT}:80"
    restart: ${RESTART}